<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('resources')->insert([
            [
                "id" => 1,
                "parent_id" => null,
                "name" => "Menu",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 2,
                "parent_id" => 1,
                "name" => "Import data",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 3,
                "parent_id" => 1,
                "name" => "Parcel",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 4,
                "parent_id" => 1,
                "name" => "Bill",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 5,
                "parent_id" => 1,
                "name" => "Payment",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 6,
                "parent_id" => 1,
                "name" => "Income / Expenses",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 7,
                "parent_id" => null,
                "name" => "Report",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 8,
                "parent_id" => 7,
                "name" => "Accounting",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 9,
                "parent_id" => 7,
                "name" => "Income / Expenses",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 10,
                "parent_id" => 7,
                "name" => "Return parcel",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 11,
                "parent_id" => null,
                "name" => "Setting",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 12,
                "parent_id" => 11,
                "name" => "Currency",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 13,
                "parent_id" => 11,
                "name" => "Customer level",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 14,
                "parent_id" => 11,
                "name" => "Customer",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 15,
                "parent_id" => 11,
                "name" => "Role & permission",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 16,
                "parent_id" => 11,
                "name" => "Department",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
            [
                "id" => 17,
                "parent_id" => 11,
                "name" => "User",
                "description" => "",
                "icon" => "",
                "path" => "",
                "sort_group" => 0,
                "active" => true,
            ],
        ]);
    }
}
